### ISSUE TITLE
Publisher spacing in the panel

### ISSUE THREAD

**Issue by NejcZdovc** [brave/browser-android-tabs#1126]
- there should be more space between image and text on the right
- more space between verified icon and `Brave verified publisher`
- verified icon has wrong color

![screenshot_20190219-083051](https://user-images.githubusercontent.com/9574457/52998151-d2b32900-3422-11e9-9753-9e548658cbc8.png)

Desktop:
![image](https://user-images.githubusercontent.com/9574457/52998185-ed859d80-3422-11e9-84f8-a5088bafef04.png)

**Comment by SergeyZhukovsky** [comment]
@jamesmudgett could you please provide the correct icon?

**Comment by SergeyZhukovsky** [comment]
Done https://github.com/brave/browser-android-tabs/commit/77e50cff07ea6c35ea92a3bbe0d2e8bdeeb2653b

**Comment by GeetaSarvadnya** [comment]
The issue is still Reproducible on 1.0.83
![screenshot_2019-03-01-01-17-40](https://user-images.githubusercontent.com/38657976/53594138-31fdff80-3bc0-11e9-99ec-f4238286697c.png)
![screenshot_2019-03-01-01-18-03](https://user-images.githubusercontent.com/38657976/53594144-36c2b380-3bc0-11e9-9729-c0c35665fc69.png)

**Comment by SergeyZhukovsky** [comment]
@GeetaSarvadnya the issue was fixed two days ago. 1.0.83 was done 3 days ago. It is not in 1.0.83.
