### ISSUE TITLE
sometimes tapping on "Claim Reward" doesn't retrieve grant

### ISSUE THREAD

**Issue by kjozwiak** [brave/browser-android-tabs#1494]
## Description 

Tapping on `Claim Reward` doesn't always claim the reward. I've ran into this several times and have been trying to debug with @SergeyZhukovsky. Once you tap the `Claim Reward` button, the UI will keep spinning with nothing happening. Eventually, it will timeout and you won't receive the BAT. Sometimes it works the second time around you get a notification, sometimes it doesn't. I ended up reproducing the issue and captured the following logs:

```
2019-04-16 11:22:08.602 3729-3743/? V/chromium: [VERBOSE1:ledger_impl.cc(1021)] 
    [ RESPONSE - setGrantCallback ]
    > time: 1555428128
    > result: Failure
    > response: {"statusCode":400,"error":"Bad Request","message":"child \"promotionId\" fails because [\"promotionId\" is not allowed to be empty]","validation":{"source":"payload","keys":["promotionId"]}}> headers cache-control: no-cache
```

## Steps to reproduce 

   1. Install `1.0.91 CR: 73.0.3683.90`
   2. once you receive the grant notification, tap on `Claim Reward`

## Actual result 

![Screenshot_20190414-205756_Brave](https://user-images.githubusercontent.com/2602313/56547746-4a4d2380-654c-11e9-9a8f-25059d735828.jpg)

## Expected result

Click on `Claim Reward` should receive the correct amount of BAT.

## Issue reproduces how often 

It's not 100% put does reproduce pretty often on my devices.

## Issue happens on 
   - Current Play Store version? Yes, reproducible using `1.0.91 CR: 73.0.3683.90`
   - Beta build? N/A (haven't tried a beta version but assuming it's still reproducible)

## Device details
   - Install type (ARM, x86): `ARM`
   - Device (Phone, Tablet, Phablet): `Samsung S10+` and `Pixel 2 XL`
   - Android version: Both running `Android 9`
   
## Brave version

Using `1.0.91 CR: 73.0.3683.90`

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? N/A
- Is the issue reproducible on the latest version of Chrome? N/A

**Comment by SergeyZhukovsky** [comment]
Fixed it here https://github.com/brave/brave-core/commit/e81b47b16f9e11d8655addc4d54c8764b3e73fc8

**Comment by kjozwiak** [comment]
@SergeyZhukovsky results so far:

**Saturday April 27th:**
* Pixel 2 XL on `android 9` using `1.0.92 CR: 73.0.3683.90` - Claimed grant without issues
* Samsung S10+ on `android 9` using `1.0.92 CR: 73.0.3683.90` - Claimed grant without issues

**Sunday April 28th:**
* Pixel 2 XL on `android 9` using `1.0.92 CR: 73.0.3683.90` - Claimed grant without issues
* Samsung S10+ on `android 9` using `1.0.92 CR: 73.0.3683.90` - Claimed grant without issues

I'll keep trying a few more times just to make sure but seems to be working. I'll mark this as `QA/Pass` once it works for another 3-4 attempts.

**Comment by kjozwiak** [comment]
Just a quick update, went through a few of the above tests during our all-hands and didn't run into any issues. Still seeing some reports that users are running into the "spinning" issue when attempting to claim grants but I haven't been running into major issues.

Going to close this off and we'll create a new issue if needed if the problem keeps being reported.

**Comment by dragGH102** [comment]
I'm having the very same issue on Oneplus 3T, Android 9. Brave 1.2.0
