### ISSUE TITLE
YT verified pubs favicon is not displayed in A-C table

### ISSUE THREAD

**Issue by GeetaSarvadnya** [brave/browser-android-tabs#1635]
## Description 

YT verified pubs favicon is not displayed in A-C table

## Steps to reproduce 

   1. Clean profile 1.0.96
   2. Open YT verified pubs https://www.youtube.com/channel/UC7J7B7PsCttOXs6qLMPetyg
   3. Watch a video for 8 secs
   

## Actual result 
YT verified puds favicon is not displayed in A-C table

![Screenshot_2019-06-04-17-27-18](https://user-images.githubusercontent.com/38657976/58877348-1558f280-86ee-11e9-9824-ee5bb6144a0d.png)

## Expected result
YT verified puds favicon should be displayed in a-c table

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? Yes
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Samsung Galaxy J3
   - Android version: 5.1.1
   
## Brave version
1.0.96

### Website problems only
- Does the issue resolve itself when disabling Brave Shields?  NA
- Is the issue reproducible on the latest version of Chrome? NA

### Additional information

@brave/legacy_qa @SergeyZhukovsky @anthonypkeane

**Comment by gdregalo** [comment]
Fixed in: https://github.com/brave/browser-android-tabs/pull/1873

**Comment by srirambv** [comment]
Still seeing the issue on 1.3.0. @gdregalo could you confirm if this was part of the onboarding build?
![Screenshot_20190805-164526](https://user-images.githubusercontent.com/17010094/62494067-955c1100-b7a0-11e9-805b-2d433549a9dc.jpg)

**Comment by srirambv** [comment]
Still doesn't look fixed. This is on the new onboarding [build ](https://github.com/brave/browser-android-tabs/releases/tag/v1.3.0)
![Screenshot_20190807-090841](https://user-images.githubusercontent.com/17010094/62625362-07dd0600-b8f3-11e9-9e48-aa7c66baddef.jpg)

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta-x64 build
  * Verified on upgrade profile, pub icon is shown for a verified YT publisher
  * Verified on upgrade profile, pub icon is not shown for non-verified YT publisher
  * Verified on a clean profile, pub icon is shown for verified YT publisher
  * Verified on a clean profile, pub icon is not shown for non-verified YT publisher
  ![image](https://user-images.githubusercontent.com/17010094/63470115-c3e11980-c439-11e9-9a13-660beac1df11.png)
