### ISSUE TITLE
Incorrect verified pub icon used in rewards panel

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#1829]
## Description 
Incorrect verified pub icon used in rewards panel

## Steps to reproduce 

   1. Enable rewards on ads build
   2. Visit a verified pub
   3. Open shields shows old verified pub icon
   4. Open ac list, shows new verified pub icon

## Actual result 
![Screenshot_20190709-100726 (1)](https://user-images.githubusercontent.com/17010094/60819430-8f591d00-a16d-11e9-956f-750d037f223a.jpg)
![Screenshot_20190709-100746 (1)](https://user-images.githubusercontent.com/17010094/60819446-954efe00-a16d-11e9-9aa3-df603a7482bb.jpg)

## Expected result
Similar to desktop
![Screenshot from 2019-07-08 10-46-27](https://user-images.githubusercontent.com/17010094/60819548-c62f3300-a16d-11e9-8dc8-970d115ac6e6.png)

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? No, uses older icon everywhere
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): All
   - Android version: All
   
## Brave version
1.1.0-8 x64 ads build

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome?

**Comment by SergeyZhukovsky** [comment]
[bat_verified.zip](https://github.com/brave/browser-android-tabs/files/3368989/bat_verified.zip)

**Comment by jamesmudgett** [comment]
![Screen Shot 2019-07-08 at 10 05 36 AM](https://user-images.githubusercontent.com/318119/60838201-bfb1b300-a18f-11e9-84f3-9ffb441ec66f.png)

**Comment by gdregalo** [comment]
@jamesmudgett @SergeyZhukovsky 
 we probably also need to update "unverified" icon
![icn_unverified](https://user-images.githubusercontent.com/37560650/61729022-5a8bbf00-ad44-11e9-8418-bb14512028fa.png)

**Comment by jamesmudgett** [comment]
[unverified_icon.zip](https://github.com/brave/browser-android-tabs/files/3424311/unverified_icon.zip)

**Comment by gdregalo** [comment]
Fixed in https://github.com/brave/browser-android-tabs/pull/1878

**Comment by srirambv** [comment]
This doesn't look fixed on 1.3.0 build. @gdregalo I still see the old hexagon icon next to the publisher in rewards panel but it has the correct icon in auto-contribute table

**Comment by srirambv** [comment]
* Verification passed on OnePlust 6T with Android 9.0 running 1.3.0-beta-x64 build
![image](https://user-images.githubusercontent.com/17010094/63471872-72875900-c43e-11e9-9b20-d3165789506e.png)

@jamesmudgett @gdregalo there seems to be very less padding between the icon and the text as compared to desktop screenshot. Is this expected for Android or can a little padding be added next to the icon?

**Comment by srirambv** [comment]
* Verification passed on Samsung Tab A with Android 9.0 running 1.3.0-beta-x64 build
![image](https://user-images.githubusercontent.com/17010094/63544716-c99b3580-c4f3-11e9-8457-366415982c02.png)
