### ISSUE TITLE
Version 1.6.2 to crashes from GP Console

### ISSUE THREAD

**Issue by AlexeyBarabash** [brave/browser-android-tabs#2435]
Top crashes for 14 days on 1.6.2

**1** 
```
backtrace:
  #00  pc 000000000150cdf8  /data/app/com.brave.browser-hM7xGPSGwTNpiRTOJwSKng==/base.apk (offset 0x50f4000)

Stack Trace:
  RELADDR   FUNCTION                                       FILE:LINE
  000000000150cdf8  bat_ledger::LedgerImpl::OnTimer(unsigned int)  ../../brave/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc:717:27
```

**2**
```
backtrace:
  #00  pc 0000000001eac76a  /data/app/com.brave.browser-rueSVqMAPJJxO3khq-eSEg==/base.apk (offset 0x50f4000)

Stack Trace:
  RELADDR   FUNCTION                                                     FILE:LINE
  v------>  logging::LogMessage::~LogMessage()::$_2::operator()() const  ../../base/logging.cc:954:7
  0000000001eac76a  logging::LogMessage::~LogMessage()                           ../../base/logging.cc:954:7
v8::internal::Isolate*)  ../../v8/src/runtime/runtime-regexp.cc:1911:1
```

**3**
app version 394510002 arm, mono
```
backtrace:
  #00  pc 0000000001501988  /data/app/com.brave.browser-ySbcdux4VH_TH32LDOYCxg==/base.apk (offset 0xb7e000)


Stack Trace:
  RELADDR   FUNCTION                                       FILE:LINE
  0000000001501988  bat_ledger::LedgerImpl::OnTimer(unsigned int)  ../../brave/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc:717:27
DEBUG:root:Finished resolving symbols. Elapsed time: 0.7273s
```

**4**
app version 394510032 arm64, mono

```
backtrace:
  #00  pc 0000000001535bac  /data/app/com.brave.browser-uIg8MV23dxEMoK-l1wZtOg==/base.apk (offset 0x50f4000)
  #01  pc 00000000fffffff4  <unknown>

Stack Trace:
  RELADDR   FUNCTION                              FILE:LINE
  0000000001535bac  ads::AdsImpl::GetWinningCategories()  ../../brave/vendor/bat-native-ads/src/bat/ads/internal/ads_impl.cc:793:36
  00000000fffffff4                                        <unknown>
```

**5**
app version 394510002, arm mono

```
backtrace:
  #00  pc 00000000015024f8  /data/app/com.brave.browser-O0Gaj1MQSA8FasUId-F2mA==/base.apk (offset 0xb7e000)
  #01  pc 000000000382c593  /data/app/com.brave.browser-O0Gaj1MQSA8FasUId-F2mA==/base.apk (offset 0xb7e000)

Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  00000000015024f8  bat_ledger::LedgerImpl::GetTransactionHistory(std::__1::function<void (std::__1::unique_ptr<ledger::TransactionsInfo, std::__1::default_delete<ledger::TransactionsInfo> >)>)  ../../brave/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc:1213:23
  000000000382c593  bat_ledger::BatLedgerImpl::GetTransactionHistory(base::OnceCallback<void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>)  ../../brave/components/services/bat_ledger/bat_ledger_impl.cc:510:12
```

**6**
app version 394510032, arm64 mono
```
backtrace:
  #00  pc 000000000150cdf8  /data/app/com.brave.browser-xX2_6IMzwZ2aznpPtWdSSw==/base.apk (offset 0x50f4000)
  #01  pc 0000000001e29e69  /data/app/com.brave.browser-xX2_6IMzwZ2aznpPtWdSSw==/base.apk (offset 0x50f4000)

Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  000000000150cdf8  bat_ledger::LedgerImpl::OnTimer(unsigned int)                                     ../../brave/vendor/bat-native-ledger/src/bat/ledger/internal/ledger_impl.cc:717:27
  0000000001e29e69  bat_ledger::mojom::BatLedgerStubDispatch::Accept(bat_ledger::mojom::BatLedger*, mojo::Message*)  android_clang_arm/gen/brave/components/services/bat_ledger/public/interfaces/bat_ledger.mojom.cc:0:0
```

**7**
app version 394510002, arm mono
```
backtrace:
  #00  pc 000000000152a73c  /data/app/com.brave.browser-b8j0SbTdu2Qh_0hpGxbGdA==/base.apk (offset 0xb7e000)
  #01  pc 00000000fffffff4  <unknown>

Stack Trace:
  RELADDR   FUNCTION                              FILE:LINE
  000000000152a73c  ads::AdsImpl::GetWinningCategories()  ../../brave/vendor/bat-native-ads/src/bat/ads/internal/ads_impl.cc:793:36
  00000000fffffff4                                        <unknown>
DEBUG:root:Finished resolving symbols. Elapsed time: 0.7368s
```

**8**
app version 394510032, arm64 mono
```
java.lang.RuntimeException: 
  at android.app.ActivityThread.callActivityOnStop (ActivityThread.java:5226)
  at android.app.ActivityThread.handleSleeping (ActivityThread.java:5358)
  at android.app.ActivityThread.access$3600 (ActivityThread.java:292)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2312)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:213)
  at android.app.ActivityThread.main (ActivityThread.java:8147)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
Caused by: java.lang.RuntimeException: 
  at org.chromium.content.browser.androidoverlay.DialogOverlayCore.assertProperThread (DialogOverlayCore.java:314)
  at org.chromium.content.browser.androidoverlay.DialogOverlayCore.access$000 (DialogOverlayCore.java:31)
  at org.chromium.content.browser.androidoverlay.DialogOverlayCore$Callbacks.surfaceDestroyed (DialogOverlayCore.java:177)
  at android.view.ViewRootImpl.notifySurfaceDestroyed (ViewRootImpl.java:2967)
  at android.view.ViewRootImpl.setWindowStopped (ViewRootImpl.java:1665)
  at android.view.WindowManagerGlobal.setStoppedState (WindowManagerGlobal.java:706)
  at android.view.WindowManagerGlobal.setStoppedState (WindowManagerGlobal.java:710)
  at android.app.Activity.performStop (Activity.java:8293)
  at android.app.ActivityThread.callActivityOnStop (ActivityThread.java:5218)
  at android.app.ActivityThread.handleSleeping (ActivityThread.java:5358)
  at android.app.ActivityThread.access$3600 (ActivityThread.java:292)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2312)
  at android.os.Handler.dispatchMessage (Handler.java:107)
  at android.os.Looper.loop (Looper.java:213)
  at android.app.ActivityThread.main (ActivityThread.java:8147)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
```

**9**
app version 394510032, arm64 mono
```
backtrace:
  #00  pc 0000000003678eee  /data/app/com.brave.browser-VjXqEB-9LCyFae8ynVWmLA==/base.apk (offset 0x50f4000) (Java_J_N_MywxQQ_00024n+12)

Stack Trace:
  RELADDR   FUNCTION                                                                          FILE:LINE
  v------>  std::__1::vector<std::__1::unique_ptr<bookmarks::BookmarkNode, std::__1::default_delete<bookmarks::BookmarkNode> >, std::__1::allocator<std::__1::unique_ptr<bookmarks::BookmarkNode, std::__1::default_delete<bookmarks::BookmarkNode> > > >::size() const  ../../buildtools/third_party/libc++/trunk/include/vector:656:61
  v------>  BookmarkBridge::GetChildCount(_JNIEnv*, base::android::JavaParamRef<_jobject*> const&, long long, int)  ../../chrome/browser/android/bookmarks/bookmark_bridge.cc:436:32
  0000000003678eee  Java_J_N_MywxQQ_00024n                                                            android_clang_arm/gen/chrome/android/chrome_jni_headers/BookmarkBridge_jni.h:199:18
DEBUG:root:Finished resolving symbols. Elapsed time: 0.7419s```
```

**10**
app version 394510032, arm64 mono
```
backtrace:
  #00  pc 0000000001eac76a  /data/app/com.brave.browser-1/base.apk (offset 0x50f4000)
  #01  pc 0000000000046f89  /system/lib/libc.so (_ZL20__pthread_cond_pulseP23pthread_cond_internal_ti+60)

Stack Trace:
  RELADDR   FUNCTION                                                     FILE:LINE
  v------>  logging::LogMessage::~LogMessage()::$_2::operator()() const  ../../base/logging.cc:954:7
  0000000001eac76a  logging::LogMessage::~LogMessage()                           ../../base/logging.cc:954:7
  0000000000046f89  <UNKNOWN>                                                    /system/lib/libc.so

```

**Comment by AlexeyBarabash** [comment]
Found a  proper way to get stack on arm64 mono build and updated symbolized stacks  above.

**Comment by kjozwiak** [comment]
@AlexeyBarabash do we know the cause of the crash? Is this something we should get fixed and pushed in the `79.0.3945.116` release? CCing @SergeyZhukovsky @anthonypkeane.

**Comment by AlexeyBarabash** [comment]
@kjozwiak unfortunately we don't know the cause of crash. We know just few last calls before crash and we can look on Android version and the device model. We cannot get STR or some other details related to crash.

**Comment by tmancey** [comment]
@AlexeyBarabash Crashes 1, 3, 5 & 6 should be resolved by https://github.com/brave/brave-core/pull/4370/files

I am now investigating crashes 4 & 7

**Comment by srirambv** [comment]
@btlechowski @GeetaSarvadnya Test for ads as part of manual pass is to be done to verify this issue. For more detailed steps please check https://github.com/brave/brave-core/pull/4370.

**Comment by AlexeyBarabash** [comment]
Have stats from 1.7.0 https://github.com/brave/browser-android-tabs/issues/2465 

Confirming
**1, 3, 5, 6, 9** which were declared as fixed - don't appear in 1.7.0 
**4, 7** - still appears in 1.7.0
**2, 10** - don't appear in 1.7.0, but were not declared as fixed

cc @kjozwiak @tmancey

**Comment by tmancey** [comment]
@AlexeyBarabash I am investigating 4 & 7 and will update as I find more, thanks

**Comment by bbondy** [comment]
Are the remaining crashes posted? I just want to make sure we're not working on crashes only mentioned in a closed issue.
cc @tmancey

**Comment by tmancey** [comment]
@bbondy Raised https://github.com/brave/brave-browser/issues/7866 to fix issues as we have seen same crashes on desktop

**Comment by tmancey** [comment]
4 and 7 fixed by https://github.com/brave/brave-browser/issues/7866
