### ISSUE TITLE
Please allow backups

### ISSUE THREAD

**Issue by mdirik** [brave/browser-android-tabs#329]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Please enable "android:allowBackup" property in release builds. This property allows backing up and restoring Brave user data using "adb backup" command line tool.

Enabling this feature should not introduce security concerns since users must enable USB debugging and unlock their devices before each backup & restore operations.

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Phone
   - Android Version: 7.0 
    
**Brave Version:** 
1.0.27

**Steps to reproduce:**
    1. Establish adb connection between phone and computer
    2. Run `` adb backup com.brave.browser ``
    3. Unlock the phone and confirm backup

**Actual Behavior**

Invalid backup file is produced

**Expected Behavior**

A valid backup file should be produced.

**Is this an issue with Beta build?**

Not tested with Beta build

**Is this an issue in the currently released version?**

Yes

**Can this issue be consistently reproduced?**

Yes

**Comment by thestinger** [comment]
I don't think a blanket allow for backups is the right approach. It's supposed to use a custom backup agent:

```
        {% if backup_key is defined %}
        android:allowBackup="true"
        android:backupAgent="org.chromium.chrome.browser.ChromeBackupAgent"
        android:fullBackupOnly="false"
        android:restoreAnyVersion="true"
        {% else %}
        android:allowBackup="false"
        {% endif %}
```

**Comment by thestinger** [comment]
I expect that the reason for this is that Android's backup/restore can interact poorly with sync mechanisms and Brave has their own sync mechanism which may present the same issues.

**Comment by mdirik** [comment]
I'm not interested in syncing or cloud backups, I'm interested in full adb backups. Brave should empower its users by allowing them to locally backup their profiles.

**Comment by thestinger** [comment]
It's not disabled to take away power from users. They can support adb backups while also determining why Chromium is disabling it and making sure the problems it's avoiding with this (bad interactions with sync, etc.) are resolved another way.

**Comment by brn238** [comment]
Can anyone confirm if adb backups are still not allowed in the release build two years later?
I am asking because I would like to extract my browser history database file in order to check the time of access to a particular website. Access times are not displayed in the history screen on the mobile version, but I believe they might be saved in the database, so this is the only way to confirm this that I can think of for now.

**Comment by mdirik** [comment]
> Can anyone confirm if adb backups are still not allowed in the release build two years later?

It is still not allowed
