### ISSUE TITLE
Panopticlick issues

### ISSUE THREAD

**Issue by SergeyZhukovsky** [brave/browser-android-tabs#520]
# Test Plan
Running fingerprint test should result like this
![image](https://user-images.githubusercontent.com/17010094/36142055-fa5d994c-10cc-11e8-8dbf-efcabb57b23b.png)
# 

# Original Issue

Please check why do we show different values for desktop and Android
https://twitter.com/BraveSampson/status/957693627903500288

**Comment by eljuno** [comment]
+1 from Twitter https://twitter.com/thinkMoult/status/959975629151072256

**Comment by SergeyZhukovsky** [comment]
That's fixed https://github.com/brave/browser-android-tabs/pull/545

**Comment by samartnik** [comment]
Needs more investigation as it causes problems https://github.com/brave/browser-android-tabs/issues/554

**Comment by samartnik** [comment]
This is waiting for completion of this issue https://github.com/brave/ad-block/issues/93

**Comment by samartnik** [comment]
Was fixed in the context of this issue https://github.com/brave/browser-android-tabs/issues/631

**Comment by Brave-Matt** [comment]
I still see users reports of this, and when testing on my end, results come back showing unique fingerprint, in addition to other detected data:
![image](https://user-images.githubusercontent.com/3299098/53995001-a0731e00-40e8-11e9-82ae-ced4738d4f73.png)
![image](https://user-images.githubusercontent.com/3299098/53995009-a832c280-40e8-11e9-8a95-919bb096e36f.png)

**Comment by srirambv** [comment]
@diracdeltas does [this](https://github.com/brave/browser-laptop/issues/5975#issuecomment-264524964) same statemtent holds good still?
