### ISSUE TITLE
Same device gets added twice when app is relaunched after enabling sync

### ISSUE THREAD

**Issue by srirambv** [brave/browser-android-tabs#854]
**Did you search for similar issues before submitting this one?**
Yes

**Description:**
Same device gets added twice when app is relaunched after enabling sync

**Device Details:**
   - Install Type(ARM, x86): ARM
   - Device(Phone, Tablet, Phablet): Tablet
   - Android Version: 8.1
    
**Brave Version:**
1.0.62(sync1)

**Steps to reproduce:**
    1. Clean install sync build
    2. Enable Sync by adding a device name or use the placeholder text as device name
    3. Wait for a couple of mins, device name doesn't show up 
    4. Remove app from memory 
    5. Re-enable sync with default placeholder device name
    6. Wait for the device list to be loaded, shows `Android device (this device)` twice

**Actual Behavior**
![image](https://user-images.githubusercontent.com/17010094/48511109-c74cd200-e823-11e8-90d7-6eef70390940.png)
Adding a desktop to the sync chain shows both entries from Android
![image](https://user-images.githubusercontent.com/17010094/48511168-fc592480-e823-11e8-997d-f98ce969617d.png)

**Expected Behavior**
Sync creation should only create one device 

**Is this an issue with Beta build?**
Yes

**Is this an issue in the currently released version?**
N/A

**Can this issue be consistently reproduced?**
Yes

**Extra QA steps:**
    1. 
    2. 
    3.

**Website problems only:**
  - did you check with Brave Shields down?
  - did you check in Chrome for same behavior?

**Screenshot if needed:**
See Actual result section

**Any related issues:**

**Comment by srirambv** [comment]
This issue is still reproducible on 1.0.62(sync1) build

**Comment by srirambv** [comment]
This can also be reproduced if the device is offline when sync is enabled for the first time and when device goes online sync chain is created and has duplicate entries

**Comment by srirambv** [comment]
This is fixed on 1.0.71(sync1) build. Verified both scenarios from original issue and offline scenario

**Comment by btlechowski** [comment]
Verified on Samsung s7 (ARM), Brave 1.0.75.

I found a case in which the issue still reproduces. Logged: https://github.com/brave/browser-android-tabs/issues/1065
